### ISSUE TITLE
wrong L5Q code generation?

### ISSUE THREAD

**Issue by mvillion** [pmonta/GNSS-DSP-tools#5]
Hello!

def make_l5q(prn):
  xb_offset = l5q_init[prn]
  n = code_length
  xb_shift = xb[np.mod(np.arange(xb_offset,xb_offset+n),n)]
  return np.logical_xor(xa,xb_shift)

Periodicity of of xb is 2**13-1 (8191), thus the correct xb_shift should be (?):
  xb_shift = xb[np.mod(np.arange(xb_offset,xb_offset+n), 8191)]

Here is another source for comparison:
https://github.com/danipascual/GNSS-matlab/tree/master/prn_codes

**Comment by pmonta** [comment]
Thanks for pointing this out.  I've checked in a fix, and the codes are now identical to the Matlab file you mention.

The L5 codes were partially correct before, so acquisition and tracking were possible but with degraded SNR.  It would have been helpful for the ICD to show the final few bits of the various codes in addition to the starting bits, to make verification more sure.  Even so, it's certainly my fault, and perhaps I should have derived the codes from sky recordings as a check.
